import { describe,expect,it } from 'vitest'
import { enrichBranches } from './branches'
import type { DialogueLine } from '../types'

const line=(nodeId:string,nextNodeId:string,text:string,extra:Partial<DialogueLine>={}):DialogueLine=>({key:nodeId,nodeId,nextNodeId,variant:0,kind:'dialogue',speaker:{zh:'',en:''},text:{zh:text,en:text},sourceType:'SingleDialog',...extra})

describe('enrichBranches',()=>{
  it('does not treat consecutive role-less monologue as options',()=>{const result=enrichBranches([line('1','2','（独白一）'),line('2','3','（独白二）')]);expect(result.every((item)=>!item.branchGroupId&&item.kind==='dialogue')).toBe(true)})
  it('keeps distinct responses inside each branch until the merge node',()=>{const selector='10-player';const result=enrichBranches([line('10','11','问句'),line('11','12','选项一'),line('12','16','回应一'),line('13','14','选项二'),line('14','16','回应二'),line('16','17','共同后续'),line(selector,'11','选项一',{nodeId:selector,key:'s0',sourceType:'MultiDialog',kind:'choice'}),line(selector,'13','选项二',{nodeId:selector,key:'s1',variant:1,sourceType:'MultiDialog',kind:'choice'})]);expect(result.find((item)=>item.nodeId==='12')?.branchRole).toBe('response');expect(result.find((item)=>item.nodeId==='14')?.branchIndex).toBe(1);expect(result.find((item)=>item.nodeId==='16')?.branchGroupId).toBeUndefined();expect(result.some((item)=>item.nodeId.endsWith('-player'))).toBe(false)})
  it('marks the triggering question and all three distinct answers',()=>{const selector='59-player';const result=enrichBranches([line('59',selector,'你会支持「莱莱可」吗？'),line('60','61','可以理解吧。'),line('61','66','回应一'),line('62','63','或许有内情。'),line('63','66','回应二'),line('64','65','有点太极端了。'),line('65','66','回应三'),line('66','67','共同后续'),line(selector,'60','可以理解吧。',{nodeId:selector,key:'s0',sourceType:'MultiDialog',kind:'choice'}),line(selector,'62','或许有内情。',{nodeId:selector,key:'s1',variant:1,sourceType:'MultiDialog',kind:'choice'}),line(selector,'64','有点太极端了。',{nodeId:selector,key:'s2',variant:2,sourceType:'MultiDialog',kind:'choice'})]);expect(result.find((item)=>item.nodeId==='59')?.branchRole).toBe('prompt');expect(result.filter((item)=>item.branchRole==='option')).toHaveLength(3);expect(result.filter((item)=>item.branchRole==='response')).toHaveLength(3);expect(result.find((item)=>item.nodeId==='66')?.branchGroupId).toBeUndefined()})
  it('marks a repeatable question menu without inventing a merge',()=>{const selector='20-player';const result=enrichBranches([line('21','22','问题一'),line('22',selector,'回答一'),line('23','24','退出'),line('24','finish','再见'),line(selector,'21','问题一',{nodeId:selector,key:'s0',sourceType:'MultiDialog',kind:'choice'}),line(selector,'23','退出',{nodeId:selector,key:'s1',variant:1,sourceType:'MultiDialog',kind:'choice'})]);expect(result.find((item)=>item.nodeId==='21')?.branchFlow).toBe('loop');expect(result.find((item)=>item.nodeId==='22')?.branchRole).toBe('response');expect(result.find((item)=>item.nodeId==='21')?.branchMergeNodeId).toBeUndefined()})
  it('marks branches that independently reach a recorded finish',()=>{const selector='30-player';const result=enrichBranches([line('31','finish','独立结局一'),line('32','finish','独立结局二'),line(selector,'31','选择一',{nodeId:selector,key:'s0',sourceType:'MultiDialog',kind:'choice'}),line(selector,'32','选择二',{nodeId:selector,key:'s1',variant:1,sourceType:'MultiDialog',kind:'choice'})]);expect(result.find((item)=>item.nodeId==='31')?.branchFlow).toBe('independent');expect(result.find((item)=>item.nodeId==='32')?.branchFlow).toBe('independent')})
  it('does not claim an ending when the upstream next node is missing',()=>{const selector='40-player';const result=enrichBranches([line('41','missing-1','路径一'),line('42','missing-2','路径二'),line(selector,'41','选择一',{nodeId:selector,key:'s0',sourceType:'MultiDialog',kind:'choice'}),line(selector,'42','选择二',{nodeId:selector,key:'s1',variant:1,sourceType:'MultiDialog',kind:'choice'})]);expect(result.find((item)=>item.nodeId==='41')?.branchFlow).toBe('unresolved');expect(result.find((item)=>item.nodeId==='42')?.branchFlow).toBe('unresolved')})
  it('uses Honey multi-next graph and leaves the merge outside the branch',()=>{const result=enrichBranches([line('50','51','prompt',{nextNodeIds:['51','53']}),line('51','52','option 1'),line('52','55','response 1'),line('53','54','option 2'),line('54','55','response 2'),line('55','56','common')]);expect(result.find((item)=>item.nodeId==='50')?.branchRole).toBe('prompt');expect(result.find((item)=>item.nodeId==='52')?.branchRole).toBe('response');expect(result.find((item)=>item.nodeId==='54')?.branchIndex).toBe(1);expect(result.find((item)=>item.nodeId==='55')?.branchGroupId).toBeUndefined();expect(result.find((item)=>item.nodeId==='50')?.branchMergeNodeId).toBe('55')})
  it('does not pull sequential common lines into an immediate choice',()=>{const result=enrichBranches([line('60','61','prompt',{nextNodeIds:['61','62']}),line('61','63','option 1'),line('62','63','option 2'),line('63','64','common'),line('64','65','more common')]);expect(result.filter((item)=>item.branchRole==='option')).toHaveLength(2);expect(result.find((item)=>item.nodeId==='63')?.branchGroupId).toBeUndefined();expect(result.find((item)=>item.nodeId==='64')?.branchGroupId).toBeUndefined()})
})
