import { chromium } from 'playwright'
import { createServer } from 'node:http'
import { mkdir, readFile } from 'node:fs/promises'
import { extname, join } from 'node:path'

const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.woff':'font/woff'}
await mkdir(join(process.cwd(),'artifacts'),{recursive:true})
const server=createServer(async(request,response)=>{ try { const pathname=new URL(request.url,'http://local').pathname;if(pathname==='/api/catalog'){response.writeHead(503).end();return}const requested=pathname==='/'?'index.html':pathname.slice(1);const path=join(process.cwd(),'dist',requested);const body=await readFile(path).catch(()=>readFile(join(process.cwd(),'dist/index.html')));response.writeHead(200,{'content-type':types[extname(path)]||'application/octet-stream'});response.end(body)}catch{response.writeHead(500).end()} })
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const port=server.address().port
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}})
await page.addInitScript(()=>localStorage.setItem('teyvat:settings:v5',JSON.stringify({guideReader:false,guideCatalog:false,guideScenes:false})))
await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'})
const controls=await page.locator('.catalog-controls').evaluate((node)=>({width:node.getBoundingClientRect().width,height:node.getBoundingClientRect().height,searchWidth:node.querySelector('.catalog-search').getBoundingClientRect().width,searchHeight:node.querySelector('.catalog-search').getBoundingClientRect().height,strayZero:[...node.childNodes].some((child)=>child.nodeType===3&&child.textContent.trim()==='0')}))
await page.evaluate(()=>sessionStorage.setItem('teyvat:catalog:types',JSON.stringify(['lq'])));await page.reload({waitUntil:'networkidle'});const storyCard=page.locator('.catalog-card').filter({hasText:'#2088'}).first();await storyCard.scrollIntoViewIfNeeded();const storyText=await storyCard.innerText();await page.evaluate(()=>sessionStorage.setItem('teyvat:catalog:types',JSON.stringify(['hq'])));await page.reload({waitUntil:'networkidle'});const hangoutCard=page.locator('.catalog-card').filter({hasText:'#101401'}).first();await hangoutCard.scrollIntoViewIfNeeded();const hangoutText=await hangoutCard.innerText();await page.evaluate(()=>sessionStorage.setItem('teyvat:catalog:types','[]'));await page.reload({waitUntil:'networkidle'})
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/catalog-desktop.jpg',type:'jpeg',quality:84,fullPage:false})
const filters=page.locator('.multi-filter');await filters.nth(0).locator('.filter-trigger').click();await filters.nth(1).locator('.filter-trigger').click();const exclusiveOpen=await page.locator('.multi-filter.open').count();await page.locator('.catalog-search').click();const outsideClosed=await page.locator('.multi-filter.open').count();await page.locator('.single-filter .filter-trigger').click();const customSortVisible=await page.locator('.single-filter .filter-popover').isVisible();await page.locator('.catalog-search').click()
await page.getByRole('button',{name:/旅行历程/}).click();await page.waitForTimeout(250);const worldDetails=page.locator('.timeline-task-group.type-wq').first();if(await worldDetails.count()){await worldDetails.locator('summary').click()}const eventDetails=page.locator('.timeline-task-group.type-eq').first();if(await eventDetails.count()){await eventDetails.locator('summary').click()}const clickable={world:await page.locator('.timeline-task-group.type-wq button').count(),event:await page.locator('.timeline-task-group.type-eq button').count(),hangout:await page.locator('.timeline-task-group.type-hq button').count()}
await page.locator('.timeline-scroll').evaluate((node)=>{node.scrollLeft=900;node.dispatchEvent(new Event('scroll'))});await page.waitForTimeout(120);const synced=await page.evaluate(()=>({top:Math.round(document.querySelector('.timeline-overview').scrollLeft),body:Math.round(document.querySelector('.timeline-scroll').scrollLeft),slider:document.querySelector('.timeline-scrubber input').value}));await page.locator('.timeline-latest').click();await page.waitForTimeout(100);const latest=await page.locator('.timeline-scroll').evaluate((node)=>({left:Math.round(node.scrollLeft),max:Math.round(node.scrollWidth-node.clientWidth)}));const countryHeading=page.locator('.country-group-heading').first();await countryHeading.click();await page.waitForTimeout(320);const collapsed=await page.locator('.timeline-country-group').first().evaluate((node)=>({className:node.className,rows:getComputedStyle(node.querySelector('.country-group-reveal')).gridTemplateRows}));await page.screenshot({path:'artifacts/timeline-desktop.jpg',type:'jpeg',quality:84,fullPage:false})
await page.getByRole('button',{name:'按国家'}).click();await page.waitForTimeout(250);const nationMode={nodes:await page.locator('.timeline-node').count(),first:await page.locator('.timeline-node').first().innerText()}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(160);await page.screenshot({path:'artifacts/timeline-mobile.jpg',type:'jpeg',quality:84,fullPage:false});const mobile=await page.evaluate(()=>({pageOverflow:document.scrollingElement.scrollWidth>document.scrollingElement.clientWidth,timelineScrollable:document.querySelector('.timeline-scroll').scrollWidth>document.querySelector('.timeline-scroll').clientWidth,latestVisible:Boolean(document.querySelector('.timeline-latest'))}))
console.log(JSON.stringify({controls,storyText,hangoutText,popovers:{exclusiveOpen,outsideClosed,customSortVisible},clickable,synced,latest,collapsed,nationMode,mobile}))
await browser.close();server.close()
